*** putpixel2
    print("push 0x8000")
    print("pop es")
    print("mov bx, " .. regs[sp - 1])
    print("mov ax, " .. regs[sp])
    print("mov [es:bx], al")
    sp = sp - 2

*** setpal
    print("mov ax, " .. regs[sp])
    print("push dx")
    print("mov dx,3c8h")
    print("out dx, al")
    print("pop dx")
    print("mov ax, " .. regs[sp - 3])
    print("shr al, 2")
    print("push dx")
    print("mov dx, 3c9h")
    print("out dx, al")
    print("pop dx")
    print("mov ax, " .. regs[sp - 2])
    print("shr al, 2")
    print("push dx")
    print("mov dx,3c9h")
    print("out dx, al")
    print("pop dx")
    print("mov ax, " .. regs[sp - 1])
    print("shr al, 2")
    print("push dx")
    print("mov dx, 3c9h")
    print("out dx, al")
    print("pop dx")
    sp = sp - 4

*** flip
    print("push 0xa000")
    print("pop es")
    print("push di")
    print("push ds")
    print("push 0x8000")
    print("pop ds")
    print("xor bx, bx")
    print("xor di, di")
    print("fliploop:")
    print("mov al, [bx]")
    print("mov ah, al")
    print("mov [es:di], ax")
    print("inc bx")
    print("inc di")
    print("inc di")
    print("jnz fliploop")
    print("pop ds")
    print("pop di")

===